export const TOP_CENTER_SLUGS = new Set<string>([
  "soukya-international-holistic-health-centre-bangalore-india",
  "ayurvedagram-heritage-wellness-centre-bangalore-india",
  "sri-sri-ayurveda-hospital-bangalore-india",
  "dharamshala/himveda",
  "dharamshala/ayuskama-ayurveda",
  "somatheeram-ayurvedic-health-resort-kerala-india",
  "ayursoma-ayurveda-royal-retreat-kerala-india",
  "kairali-the-ayurvedic-healing-village-kerala-india",
  "veda5-ayurveda-and-yoga-retreat-kerala-india",
  "soul-vacation-resort-and-spa-goa-india",
  "swan-yoga-retreat-goa-india",
  "uttarakhand/ananda-in-the-himalayas",
  "delhi/namastedwaar",
  "ayurmana-dharma-ayurvedic-centre-kerala-india",
  "chamundi-hill-palace-ayurvedic-resort-mysore-india",
  "kairali-heritage-resort-kerala-india",
  "agni-ayurvedic-village-kerala-india",
  "dheemahi-ayurveda-village-kumarakom-kerala-india",
  "kumarakom-lake-resort-kerala-india",
  "nagarjuna-ayurvedic-centre-kerala-india",
  "sanjeevanam-ayurveda-hospital-kerala-india",
  "back-to-roots-ayurveda-retreat-kerala-india",
  "dhathri-ayurveda-hospital-and-retreat-kerala-india",
  "krishnendu-ayurveda-hospital-kerala-india",
  "athreya-ayurvedic-centre-kerala-india",
  "ayur-bethaniya-ayurveda-hospital-kerala-india",
  "ayushi-ayurvedic-retreat-kerala-india",
  "sitaram-mountain-retreat-idukki-india",
  "akanta-ayurveda-and-yoga-resort-kochi-india",
  "sitaram-beach-retreat-kerala-india",
  "indus-valley-ayurvedic-centre-mysore-banglore-india",
  "shathayu-ayurveda-yoga-retreat-udupi-banglore-india",
  "shreyas-yoga-retreat",
  "ananda-in-the-himalayas-uttarakhand-india",
  "ayuskama-ayurveda-and-panchakarma-center-dharamshala-india",
  "veda5-ayurveda-and-yoga-retreat-rishikesh-india",
  "yan-cure-yoga-retreat-and-ayurveda-centre-rishikesh-india",
  "namaste-dwaar-countryside-wellness-retreat-delhi-india",
  "naad-wellness-centre-sonepat-delhi-india",
  "the-imperial-spa-and-wellness-delhi-india",
  "itc-grand-bharat-wellness-retreat-gurugram-delhi-india",
  "amanbagh-heritage-wellness-retreat-rajasthan-india",
  "agni-ayurvedic-village-resort-panvel-mumbai-india",
  "fazlani-natures-nest-wellness-centre-mumbai-india",
  "viveda-wellness-village-mumbai-india",
  "dharana-at-shillim-wellness-retreat-pune-india",
  "toyam-by-orchid-hotels-wellness-resort-pune-india",
  "atmantan-wellness-resort-pune-india",
]);

export const prioritizeTopCenters = <T extends { slug?: string }>(list: T[]) => {
  const top = list.filter((center) => center.slug && TOP_CENTER_SLUGS.has(center.slug));
  const rest = list.filter((center) => !(center.slug && TOP_CENTER_SLUGS.has(center.slug)));
  return [...top, ...rest];
};
