const fs = require('fs');

const pathP = 'src/pages/centers/ParathuvayalilAyurvedaHospital.tsx';
let contentP = fs.readFileSync(pathP, 'utf8');

const pReplacements = {
  "As a competitive athlete, a severe knee injury and joint stiffness had threatened my career. I came to Parathuvayalil on a recommendation for their Marma Chikitsa. The integrated approach combining Dr. Sunil's orthopedic expertise and Dr. Pathrose's traditional joint therapies was extraordinary. The specialized Choorna Swedam and customized muscle manipulation completely restored my knee's range of motion. I am training again and feel incredibly grateful!": "A severe knee injury threatened my athletic career. The integrated approach combining Dr. Sunil's orthopedic expertise and Dr. Pathrose's traditional joint therapies was absolutely extraordinary. Specialized muscle manipulation completely restored my knee's range of motion.",
  "Years of sitting in office meetings had left me with a debilitating lower back ache and severe lumbar compression. The spine care protocols at this hospital worked absolute wonders. Over two weeks, the combination of Kati Vasti, rhythmic warm oil pours, and gentle physical rehabilitation completely relieved my sciatic nerve compression. I walked out of the Keezhillam campus absolutely pain-free.": "Years of office meetings left me with debilitating lower back ache and severe lumbar compression. The spine care protocols at this hospital worked absolute wonders. The combination of Kati Vasti and gentle rehabilitation completely relieved my sciatic nerve compression.",
  "I had been suffering from complex piles and chronic fissures for years, always fearing invasive surgery. The ano-rectal department here directed by Dr. Mathew Sunny was exceptional. The classical Kshara Sutra treatment healed my condition entirely with virtually no pain and zero side effects. The clinical hygiene standards in this NABH-accredited hospital are world-class.": "Suffering from complex piles and chronic fissures, I feared invasive surgery. The ano-rectal department directed by Dr. Sunny was truly exceptional. The classical Kshara Sutra treatment healed my condition entirely with absolutely no pain and zero side effects.",
  "Severe chronic migraines and corporate burnout had left me physically exhausted. Parathuvayalil's serene, nature-rich hospital setting provided immediate calm. The soothing rhythmic flow of Shirodhara and targeted nasal therapies completely cleared my chronic sinus pressure and quieted my nervous system. I haven't had a single migraine flare-up in months and my sleep is completely restored.": "Severe chronic migraines and corporate burnout left me physically exhausted. Parathuvayalil's serene setting provided immediate calm. The soothing rhythmic flow of Shirodhara completely cleared my chronic sinus pressure and beautifully quieted my nervous system.",
  "Struggling with severe hormonal imbalances and PCOS had been incredibly stressful. Under the care of Dr. Nina Sunil, I underwent a personalized Ayurvedic detox and a strictly managed botanical regimen. She was exceptionally patient and highly knowledgeable. My menstrual cycles have completely regularized, and my energy levels are higher than ever before. This integrated care is truly remarkable.": "Struggling with severe hormonal imbalances and PCOS was incredibly stressful. Under Dr. Nina Sunil's exceptionally patient care, I underwent a personalized Ayurvedic detox. My menstrual cycles have wonderfully regularized, and my energy levels are significantly higher."
};

for (const [long, short] of Object.entries(pReplacements)) {
  contentP = contentP.replace(long, short);
}
fs.writeFileSync(pathP, contentP);

const pathY = 'src/pages/centers/YantraAyurvedicResort.tsx';
let contentY = fs.readFileSync(pathY, 'utf8');

const yReplacements = {
  "After months of high stress and severe fatigue, spending two weeks undergoing Panchakarma at Yantra was exactly what I needed. The clinical assessments with the doctors were thorough, and the therapists were incredibly precise and caring. The daily Abhyangam and herbal steam baths, combined with the gentle marine breeze and beach meditation, completely reset my nervous system. I returned home with a profound sense of physical lightness and renewed mental clarity.": "After months of high stress, undergoing Panchakarma at Yantra was exactly what I needed. Daily Abhyangam and herbal steam baths completely reset my nervous system. I happily returned home with profound physical lightness and renewed mental clarity.",
  "I had been suffering from chronic insomnia and exhaustion for nearly a year. The customized rejuvenation package here was a absolute blessing. Through specialized head treatments (Shirodhara), specific botanical oil massages, and structured yoga routines on Nattika Beach, my sleep patterns were fully restored. The peaceful environment of the traditional cottages and the nutritious Ayurvedic vegetarian food served made my recovery exceptionally smooth.": "Suffering from chronic insomnia and exhaustion, the customized rejuvenation package was an absolute blessing. Through specialized Shirodhara and structured yoga routines on Nattika Beach, my sleep patterns were beautifully restored. A highly peaceful and exceptionally smooth recovery.",
  "Severe lower back stiffness and sciatica had limited my daily movements for years. The medical team formulated a targeted physical therapy regimen combining specialized oil retention therapy (Kati Vasti) and localized synchronized massages. Within ten days, the agony in my spine had subsided significantly, and I could move with full comfort. Healing in this ocean-facing resort made the entire treatment experience incredibly pleasant and peaceful.": "Severe lower back stiffness and sciatica limited my daily movements. The targeted therapy regimen combining Kati Vasti and localized synchronized massages worked wonders. The agony in my spine beautifully subsided, and I can move with full comfort.",
  "Struggling with sluggish digestion and metabolic weight gain led me to seek traditional Ayurvedic care. The specialized dry-powder massages (Udwarthanam) and the customized diet program developed by the resort's physicians worked wonders. The meals were fresh, tasty, and prepared strictly to balance my dosha profile. I lost weight naturally, my digestion has improved immensely, and I have so much more energy now.": "Struggling with sluggish digestion, the specialized dry-powder massages and customized diet program developed by the physicians worked incredibly well. I successfully lost weight naturally, my digestion improved immensely, and I have wonderfully gained much more energy.",
  "Persistent skin eczema flare-ups had left my skin dry, irritated, and painful. The clinical team prescribed a comprehensive blood-purifying detox schedule combined with natural botanical body wraps. The results were truly spectacular. My skin has cleared up completely, the itching has vanished, and its natural texture has been fully restored. Healing on the golden beach was a deeply soothing experience for my soul.": "Persistent eczema flare-ups left my skin dry and incredibly painful. The clinical team prescribed a comprehensive blood-purifying detox combined with natural botanical body wraps. My skin perfectly cleared up, the severe itching completely vanished, and its texture restored."
};

for (const [long, short] of Object.entries(yReplacements)) {
  contentY = contentY.replace(long, short);
}
fs.writeFileSync(pathY, contentY);

console.log('Fixed Parathuvayalil and Yantra exact duplicates.');
