const SLUG_BY_NAME: Record<string, string> = {
  "Agni Ayurvedic Village Resort": "kerala/agni-ayurvedic-village",
  "Fazlani Nature's Nest Wellness Center": "fazlani-natures-nest-wellness-center-mumbai-india",
  "Atmantan Wellness Resort": "atmantan-wellness-resort-pune-india",
  "Viveda Wellness Village": "viveda-wellness-village-mumbai-india",
  "Dharana At Shillim": "dharana-at-shillim-wellness-retreat-pune-india",
  "Toyam By Orchid Hotels": "toyam-by-orchid-hotels-wellness-resort-pune-india",
  "Shathayu Ayurveda Yoga Retreat": "shathayu-ayurveda-yoga-retreat-udupi-banglore-india",
  "Shreyas Yoga Retreat": "shreyas-yoga-retreat-bangalore-india",
  "Indus Valley Ayurvedic Center": "indus-valley-ayurvedic-hospital-mysore-india",
  "Sri Sri Ayurveda Hospital Bengaluru": "sri-sri-ayurveda-hospital-bengaluru-india",
  "{processInlineFormatting(titleText)}": "soukya-international-holistic-health-center-bangalore-india",
  "Vydehi Ayurveda Hospital (VAYU)": "vydehi-ayurveda-hospital-bengaluru-india",
  "AyurvedaGram": "bangalore/ayurvedagram",
  "Ananda In The Himalayas": "ananda-in-the-himalayas-uttarakhand-india",
  "Yan Cure": "yan-cure-yoga-retreat-and-ayurveda-center-rishikesh-india",
  "Soul Vacation": "soul-vacation-resort-spa-goa-india",
  "SWAN Yoga Retreat": "swan-yoga-retreat-goa-india",
  "Mercure Goa Devaaya Resort - Ayurveda Wellness Center": "mercure-goa-devaaya-retreat-goa-india",
  "Ashiyana Yoga Retreat": "ashiyana-yoga-retreat-village-goa-india",
  "Nalanda Retreat Goa": "nalanda-retreat-goa-india",
  "Modi Yoga Retreat": "rishikesh/modi-yoga-retreat",
  "Adyant Ayurveda – Jayanagar": "adyant-ayurveda-hospital-bengaluru-india",
  "ITC Grand Bharat": "itc-grand-bharat-wellness-retreat-gurugram-delhi-india",
  "Niraamaya Retreats Surya Samudra": "kerala/niraamaya-retreats-surya-samudra",
  "AMANBAGH": "amanbagh-heritage-wellness-retreat-rajasthan-india",
  "HimVeda": "dharamshala/himveda",
  "Kalari Kovilakom - The Palace For Ayurveda": "kerala/kalari-kovilakom",
  "Carnoustie Ayurveda & Wellness Resort": "kerala/carnoustie-ayurveda-wellness-resort",
  "The Nattika Beach Resort": "kerala/the-nattika-beach-resort",
  "Sitaram Beach Retreat": "kerala/sitaram-beach-retreat",
  "Ideal Ayurvedic Resort": "kerala/ideal-ayurvedic-resort",
  "Somatheeram Ayurvedic Health Resort": "kerala/somatheeram",
  "Kairali - The Ayurvedic Healing Village": "kerala/kairali-ayurvedic-healing-village",
  "Veda5": "veda5",
  "Namaste Dwaar": "delhi/namastedwaar",
  "Kairali Heritage Resort": "kerala/kairali-heritage",
  "Dheemahi Kumarakom Ayurvedic Center": "kerala/dheemahi-kumarakom",
  "Back to Roots Ayurveda Retreat": "kerala/back-to-roots",
  "Krishnendu Ayurveda Hospital": "kerala/krishnendu-ayurveda-hospital",
  "Viveda Wellness Village": "maharashtra/viveda-wellness-village",
  "NAAD WELLNESS": "sonepat/naad-wellness",
  "Dharana At Shillim": "pune/dharana-at-shillim",
  "The Imperial Spa and Wellness": "delhi/the-imperial-spa-and-wellness",
  "ITC Grand Bharat": "gurugram/itc-grand-bharat",
  "AMANBAGH": "rajasthan/amanbagh-heritage-wellness-retreat",
  "Ayuskama Ayurveda": "dharamshala/ayuskama-ayurveda",
  "AyurSoma": "kerala/ayursoma",
  "Sandhya Hot Spring Health Care": "himachal/sandhya-hot-spring-health-care",
  "Ayurmana": "kerala/ayurmana",
  "Chamundi Hill Palace": "mysore/chamundi-hill-palace",
  "Kumarakom Lake Resort": "kerala/kumarakom-lake-resort",
  "Athreya Ayurvedic Center": "kerala/athreya-ayurvedic-center",
  "Ayur Bethaniya Ayurveda Hospital": "kerala/ayur-bethaniya-ayurveda-hospital",
  "Ayushi Ayurvedic Retreat": "kerala/ayushi-ayurvedic-retreat",
  "Sitaram Mountain Retreat": "idukki/sitaram-mountain-retreat",
  "Akanta Ayurveda and Yoga Resort": "kochi/akanta-ayurveda-and-yoga-resort",
  "Indus Valley Ayurvedic Center": "mysore/indus-valley-ayurvedic-center",
  "Shathayu Ayurveda Yoga Retreat": "udupi/shathayu-ayurveda-yoga-retreat",
  "Nagarjuna Ayurveda Center": "kerala/nagarjuna-ayurveda-center",
  "Sanjeevanam Ayurveda Hospital": "kerala/sanjeevanam-ayurveda-hospital",
  "Dhathri Ayurveda Hospital & Panchakarma Center": "kerala/dhathri-ayurveda",
  "Fazlani Nature's Nest Wellness Center": "maharashtra/fazlani-natures-nest",
  "Atmantan Wellness Resort": "pune/atmantan-wellness-resort",
  "Toyam By Orchid Hotels": "pune/toyam-by-orchid-hotels",
  "Ananda In The Himalayas": "uttarakhand/ananda-in-the-himalayas",
  "Yan Cure": "rishikesh/yan-cure",
};
